networks:
  gitea-network:
    external: true
  gitea-db-network:
    external: true
  traefik-network:
    external: true
  keycloak-db-network:
    external: true
  grafana-db-network:
    external: true
  consul-network:
    driver: bridge

volumes:
  gitea-data:
  gitea-postgres:
  gitea-postgres-backup:
  gitea-data-backups:
  gitea-database-backups:
  traefik-certificates:
  traefik-certificates-proxmox:
  keycloak-db:
  grafana-data:
  grafana-db:

services:
  traefik:
    extends:
      file: docker-compose.traefik.yml
      service: traefik

  grafana:
    extends:
      file: docker-compose.grafana.yml
      service: grafana

  grafana-db:
    extends:
      file: docker-compose.grafana.yml
      service: grafana-db

  keycloak:
    extends:
      file: docker-compose.keycloak.yml
      service: keycloak

  keycloak-db:
    extends:
      file: docker-compose.keycloak.yml
      service: keycloak-db

  # gitea:
  #   extends:
  #     file: docker-compose.gitea.yml
  #     service: gitea

  # gitea-db:
  #   extends:
  #     file: docker-compose.gitea.yml
  #     service: gitea-db

  # gitea-runner:
  #   extends:
  #     file: docker-compose.gitea-runner.yml
  #     service: gitea-runner

  # traefik-proxmox:
  #   extends:
  #     file: docker-compose.traefik-proxmox.yml
  #     service: traefik  

  # consul:
  #   image: bitnami/consul:latest
  #   networks:
  #     - consul-network
  #   ports:
  #     - '8300:8300'
  #     - '8301:8301'
  #     - '8301:8301/udp'
  #     - '8500:8500'
  #     - '8600:8600'
  #     - '8600:8600/udp'