networks:
  gitea-network:
    external: true
  gitea-db-network:
    external: true
  traefik-network:
    external: true
  keycloak-db-network:
    external: true
  grafana-db-network:
    external: true
  consul-network:
    driver: bridge

volumes:
  gitea-data:
  gitea-postgres:
  gitea-postgres-backup:
  gitea-data-backups:
  gitea-database-backups:
  traefik-certificates:
  traefik-certificates-proxmox:
  keycloak-db:
  grafana-data:
  grafana-db:
  postgres:

services:
  traefik:
    extends:
      file: docker-compose.traefik.yml
      service: traefik

  redis:
    extends:
      file: docker-compose.redis.yml
      service: redis

  postgres:
    extends:
      file: docker-compose.postgres.yml
      service: postgres