---
all:
  hosts:
    server1:
      ansible_host: 1.2.3.4
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa

  vars:
    ansible_become: yes
    ansible_become_method: sudo